name: CI Pipeline for Node.js and Python

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:

            - name: Check out code  
              uses: actions/setup-node@v2
              with:
                node-version: '14'
            
            - name: Set up Node.js dependencies
              run: npm install

            - name: set up python
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'
            
            - name: Install python dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
